"""Build the full NIIMBOT M2 label library and validate every file.

Writes:
    Product Labels/VS Research Labs/<Product>/Master PNG/     three PNGs per dose
    Product Labels/VS Research Labs/<Product>/Source Images/  the vial render
    Product Labels/VS Research Labs/<Product>/Notes/          reconstruction notes
    Product Labels/VALIDATION_REPORT.md
    Product Labels/Contact Sheets/

Run:
    scripts/labels/.venv/bin/python scripts/labels/build_library.py
"""

from __future__ import annotations

import shutil
from collections import defaultdict
from dataclasses import dataclass
from pathlib import Path

import numpy as np
from PIL import Image

import build_label as B

LIBRARY = B.ROOT / "Product Labels"
BRAND_DIR = LIBRARY / "VS Research Labs"
SHEET_DIR = LIBRARY / "Contact Sheets"


@dataclass
class Check:
    name: str
    passed: bool
    detail: str = ""


def _ink(path: Path) -> np.ndarray:
    return np.asarray(Image.open(path).convert("L")) < 128


def validate_triplet(paths: dict[str, Path], label: B.Label, drawn: dict) -> list[Check]:
    checks: list[Check] = []

    for kind, path in paths.items():
        with Image.open(path) as im:
            size_ok = im.size == (B.WIDTH, B.HEIGHT)
            checks.append(
                Check(f"{kind}: 472x236", size_ok, "" if size_ok else f"got {im.size}")
            )
            checks.append(Check(f"{kind}: PNG", im.format == "PNG", str(im.format)))
            dpi = tuple(round(v) for v in im.info.get("dpi", (0, 0)))
            checks.append(
                Check(f"{kind}: 300 dpi", dpi == (B.DPI, B.DPI), "" if dpi == (300, 300) else str(dpi))
            )
            colours = np.unique(np.asarray(im.convert("RGB")).reshape(-1, 3), axis=0)
            pure = {tuple(c) for c in colours} <= {(0, 0, 0), (255, 255, 255)}
            checks.append(
                Check(
                    f"{kind}: pure B/W",
                    pure,
                    "" if pure else f"{len(colours)} colours present",
                )
            )

        ink = _ink(path)
        if ink.any():
            ys, xs = np.where(ink)
            inside = (
                xs.min() >= B.MARGIN
                and ys.min() >= B.MARGIN
                and xs.max() < B.WIDTH - B.MARGIN
                and ys.max() < B.HEIGHT - B.MARGIN
            )
            checks.append(
                Check(
                    f"{kind}: inside safe margin",
                    inside,
                    "" if inside else f"bbox {xs.min()},{ys.min()}-{xs.max()},{ys.max()}",
                )
            )
        else:
            checks.append(Check(f"{kind}: has artwork", False, "blank image"))

    master, body, bar = (_ink(paths[k]) for k in ("master", "body", "bar"))
    union_ok = bool((master == (body | bar)).all())
    checks.append(Check("registration: master == body + bar", union_ok))
    disjoint = not bool((body & bar).any())
    checks.append(Check("registration: body and bar do not overlap", disjoint))
    checks.append(Check("bar file contains only the bar", bool(bar.any()) and not bool(bar[: B.HEIGHT - B.MARGIN - B.BAR_HEIGHT - 1].any())))

    expected_name, _ = B.printable_name(label.name)
    name_ok = drawn["code"] == expected_name
    checks.append(
        Check("text: compound name matches product data", name_ok, f"drew {drawn['code']!r}")
    )
    dose_ok = drawn["dose"] == label.dose
    checks.append(Check("text: dose matches product data", dose_ok, f"drew {drawn['dose']!r}"))
    checks.append(Check("text: purity line verbatim", drawn["purity"] == "PURITY: 99.9%"))
    checks.append(
        Check(
            "text: warning line verbatim",
            drawn["warning"] == "RESEARCH USE ONLY / NOT FOR HUMAN USE",
        )
    )
    checks.append(Check("text: wordmark verbatim", drawn["wordmark"] == "RESEARCH LABS"))
    return checks


NOTES_TEMPLATE = """# {product} — label reconstruction notes

Generated by `scripts/labels/build_label.py`. Do not hand-edit the PNGs; rerun
the generator instead.

## Source of truth

Design spec taken from `scripts/vials/build_vial.py`, the generator that
produced the vial renders in `public/vials/`. Product name and dose strings come
from `src/data/{source_file}` and are compared programmatically against the
rendered label — no string was typed by hand.

Reference render: `Source Images/{source_image}`

## Doses in this folder

{dose_list}

## Typography as printed

| Element | Typeface | Size | Tracking | Alignment |
|---|---|---|---|---|
| RESEARCH LABS | Cormorant Garamond, variation weight 600 | 26 px | 3.0 | centred in type column |
| Compound name | IBM Plex Mono Medium | auto-fit 26 to 13 px, max 2 lines | 1.0 | centred in type column |
| Dose | IBM Plex Mono Medium | 0.62x compound size | 2.4 | centred in type column |
| PURITY / warning | IBM Plex Mono Medium | auto-fit 15 to 9 px | 0.3 | left |

## Flagged for review

{flags}
"""


def main() -> None:
    rows = B.load_labels()
    by_product: dict[str, list] = defaultdict(list)
    for product_name, label, image in rows:
        by_product[product_name].append((label, image))

    results: list[tuple[str, B.Label, list[Check], list[str]]] = []
    contact: list[tuple[str, Path]] = []

    for product_name, entries in by_product.items():
        product_dir = BRAND_DIR / product_name
        masters = product_dir / "Master PNG"
        sources = product_dir / "Source Images"
        notes_dir = product_dir / "Notes"
        for directory in (masters, sources, notes_dir):
            directory.mkdir(parents=True, exist_ok=True)

        flags: list[str] = []
        source_image = entries[0][1]
        src = B.ROOT / "public" / source_image.lstrip("/")
        if src.exists():
            shutil.copy2(src, sources / src.name)
        else:
            flags.append(f"- Source render `{source_image}` not found on disk; none copied.")

        for label, _ in entries:
            paths, drawn = B.render_label(label, masters)
            _, subs = B.printable_name(label.name)
            flags.extend(
                f"- Product name contains a character no bundled font can render: {note}. "
                "The label prints the ASCII spelling. Confirm this is acceptable."
                for note in subs
            )
            checks = validate_triplet(paths, label, drawn)
            results.append((product_name, label, checks, subs))
            contact.append((f"{product_name} {label.dose}", paths["master"]))
            if drawn["code_size"] <= B.CODE_SIZE_MIN + 2:
                flags.append(
                    f"- `{label.dose}`: long name set at {drawn['code_size']} px "
                    "(near the legibility floor). Consider a shorter print name."
                )

        source_file = (
            "biopeptideCompounds.generated.json"
            if (B.ROOT / "src/data/biopeptideCompounds.generated.json").exists()
            else "products.json"
        )
        (notes_dir / "RECONSTRUCTION_NOTES.md").write_text(
            NOTES_TEMPLATE.format(
                product=product_name,
                source_file=source_file,
                source_image=src.name if src.exists() else "(missing)",
                dose_list="\n".join(f"- {label.dose} → `{label.slug}_*.png`" for label, _ in entries),
                flags="\n".join(dict.fromkeys(flags)) or "- Nothing flagged.",
            )
        )

    _write_report(results)
    _write_contact_sheets(contact)
    total = len(results)
    failed = sum(1 for _, _, checks, _ in results if any(not c.passed for c in checks))
    print(f"{total} labels ({total * 3} PNGs); {total - failed} passed all checks, {failed} failed")


def _write_report(results) -> None:
    total = len(results)
    all_checks = [c for _, _, checks, _ in results for c in checks]
    failed = [(p, l, c) for p, l, checks, _ in results for c in checks if not c.passed]
    subs = [(p, l, s) for p, l, _, s in results if s]

    lines = [
        "# NIIMBOT M2 label library — validation report",
        "",
        f"- Labels: **{total}** ({total * 3} PNG files: master / body / bar)",
        f"- Individual assertions run: **{len(all_checks)}**",
        f"- Failures: **{len(failed)}**",
        "",
        "## Checks applied to every label",
        "",
        "| Check | Applies to |",
        "|---|---|",
        "| Exactly 472 x 236 px | each of the three files |",
        "| PNG container | each of the three files |",
        "| 300 dpi metadata | each of the three files |",
        "| Only pure #FFFFFF and #000000 present | each of the three files |",
        "| All ink inside the 15 px safe margin (nothing clipped) | each of the three files |",
        "| master == body + bar, pixel for pixel | the triplet |",
        "| body and bar share no ink (clean two-pass separation) | the triplet |",
        "| bar file contains only the bottom bar | the triplet |",
        "| Compound name equals the product-data string | the label |",
        "| Dose equals the product-data string | the label |",
        "| PURITY / warning / wordmark strings verbatim | the label |",
        "",
    ]

    if failed:
        lines += ["## Failures", "", "| Product | Dose | Check | Detail |", "|---|---|---|---|"]
        lines += [f"| {p} | {l.dose} | {c.name} | {c.detail} |" for p, l, c in failed]
    else:
        lines += ["## Failures", "", "None. Every assertion passed on every file.", ""]

    lines += ["", "## Flagged for Ray's review", ""]
    if subs:
        lines += [
            "**Character substitutions** (the bundled fonts have no glyph, so the label "
            "would otherwise print an empty box):",
            "",
        ]
        lines += [f"- {p} ({l.dose}): {'; '.join(s)}" for p, l, s in subs]
        lines.append("")

    lines += [
        "**Fields the current design does not have.** These are absent from the vial "
        "design in `scripts/vials/build_vial.py` and were faithfully omitted rather "
        "than invented. If any are wanted, here is where they fit in the landscape layout:",
        "",
        "| Field | Present? | Where it could go |",
        "|---|---|---|",
        "| Lot / batch number | No | Right end of the purity line, e.g. `PURITY: 99.9%    LOT 24-0142`; there is spare width there. |",
        "| Expiry / retest date | No | Second slot on the purity line, or replacing the dose line's right margin. |",
        "| QR code | No | Would need a real redesign: a 40 x 40 px quiet-zone QR only fits by dropping the mark to ~56 px, which costs the ring. Better on a second label. |",
        "| Barcode (Code 128) | No | Same constraint as the QR. A 2:1 landscape at 40 x 20 mm has no room for a scannable barcode alongside this lockup. |",
        "| Hazard / storage icons | No | Left of the warning line, at roughly 14 px square, replacing the leading indent. |",
        "",
        "**Products deliberately excluded.** Lab equipment, bacteriostatic water, "
        "acetic acid and syringes carry no vial render and no 99.9% purity claim, so "
        "they get no label from this run.",
        "",
        "## Per-label results",
        "",
        "| Product | Dose | Printed name | Checks | Result |",
        "|---|---|---|---|---|",
    ]
    for product, label, checks, _ in sorted(results, key=lambda r: (r[0], r[1].dose)):
        bad = [c for c in checks if not c.passed]
        printed, _ = B.printable_name(label.name)
        status = "PASS" if not bad else f"FAIL ({len(bad)})"
        lines.append(f"| {product} | {label.dose} | {printed} | {len(checks)} | {status} |")

    (LIBRARY / "VALIDATION_REPORT.md").write_text("\n".join(lines) + "\n")


def _write_contact_sheets(contact: list[tuple[str, Path]]) -> None:
    SHEET_DIR.mkdir(parents=True, exist_ok=True)
    cols, per_sheet = 3, 24
    pad = 12
    cell_w, cell_h = B.WIDTH + pad, B.HEIGHT + pad + 16
    for index in range(0, len(contact), per_sheet):
        chunk = contact[index : index + per_sheet]
        rows = (len(chunk) + cols - 1) // cols
        sheet = Image.new("RGB", (cols * cell_w + pad, rows * cell_h + pad), "#b9bcc4")
        for i, (_, path) in enumerate(chunk):
            x = pad + (i % cols) * cell_w
            y = pad + (i // cols) * cell_h
            sheet.paste(Image.open(path), (x, y))
        sheet.save(SHEET_DIR / f"contact_sheet_{index // per_sheet + 1:02d}.png")


if __name__ == "__main__":
    main()
