import { chromium } from 'playwright';
const URL = process.env.URL || 'http://localhost:4173';
const b = await chromium.launch({ headless: true, args: ['--use-gl=swiftshader', '--enable-unsafe-swiftshader'] });
const ctx = await b.newContext({ viewport: { width: 390, height: 780 } }); // phone-ish, fresh (no storage)
const p = await ctx.newPage();
await p.goto(URL, { waitUntil: 'domcontentloaded' });
await p.waitForTimeout(1800);
const gateShown = await p.locator('text=Research-Use Only').count();
const boxes = p.locator('input[type="checkbox"]');
const n = await boxes.count();
for (let i = 0; i < n; i++) await boxes.nth(i).check().catch(() => {});
await p.getByRole('button', { name: /enter site/i }).click().catch(() => {});
await p.waitForTimeout(900);
const overflowWhileIntro = await p.evaluate(() => document.body.style.overflow);
await p.locator('[aria-label="Dismiss intro"]').click().catch(() => {});
await p.waitForTimeout(900);
const overflowAfter = await p.evaluate(() => document.body.style.overflow);
const scrolledTo = await p.evaluate(() => { window.scrollTo(0, 500); return window.scrollY; });
console.log(JSON.stringify({ gateShown: gateShown > 0, checkboxes: n, overflowWhileIntro: overflowWhileIntro || '(empty)', overflowAfter: overflowAfter || '(empty)', scrolledTo }, null, 2));
await b.close();
